
server:
  port: 8081
spring:  
  datasource:
    url: jdbc:postgresql://localhost:5432/learning  
    username: postgres  
    password: root  
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true  
    properties:
      hibernate:
        format_sql: true  
        dialect: org.hibernate.dialect.PostgreSQLDialect  

  kafka:
    consumer:
      group-id: enrollment-group  
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      bootstrap-servers: kafka:9092  
      

  logging:
    level:
      org.springframework.web: DEBUG  
      org.hibernate.SQL: DEBUG  
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE  